/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view;

import dao.DiagnosticoDao;
import dao.DoencaDao;
import dao.ProntuarioDao;
import javax.swing.JDesktopPane;
import javax.swing.JOptionPane;
import modelo.Diagnostico;
import modelo.Doenca;
import modelo.Prontuario;

/**
 *
 * @author blank
 */
public class TelaDiagnostico extends javax.swing.JInternalFrame {

    private JDesktopPane painel;
    
    public TelaDiagnostico() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnVoltar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnProntuario = new javax.swing.JButton();
        btnDoenca = new javax.swing.JButton();
        lblProntuario = new javax.swing.JLabel();
        lblDoenca = new javax.swing.JLabel();
        lblIdProntuario = new javax.swing.JLabel();
        lblIdDoenca = new javax.swing.JLabel();
        comboStatus = new javax.swing.JComboBox<>();

        jPanel1.setBackground(new java.awt.Color(254, 254, 254));

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        btnInserir.setText("Inserir");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });

        btnProntuario.setText("Selecionar Prontuario");
        btnProntuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProntuarioActionPerformed(evt);
            }
        });

        btnDoenca.setText("Selecionar Doença");
        btnDoenca.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDoencaActionPerformed(evt);
            }
        });

        lblProntuario.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblProntuario.setText("Nenhum");

        lblDoenca.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblDoenca.setText("Nenhuma");

        lblIdProntuario.setText("0");

        lblIdDoenca.setText("0");

        comboStatus.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Não Solucionado", "Solucionado", " " }));
        comboStatus.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                comboStatusActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGap(77, 77, 77)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 126, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblIdProntuario, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblIdDoenca, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(57, 57, 57))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(27, 27, 27)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(btnProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 180, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 198, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(46, 46, 46)
                .addComponent(btnProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblProntuario, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdProntuario))
                .addGap(29, 29, 29)
                .addComponent(btnDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblDoenca, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblIdDoenca))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboStatus, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnVoltarActionPerformed

    public void defineProntuario(String dataEntrada, String idProntuario){
        lblProntuario.setText(dataEntrada);
        lblIdProntuario.setText(idProntuario);
    }
    
    public void defineDoenca(String doenca, String idDoenca){
        lblDoenca.setText(doenca);
        lblIdDoenca.setText(idDoenca);
    }
    
    private void btnProntuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProntuarioActionPerformed
        TelaListarPacient telaPaciente = new TelaListarPacient();
        telaPaciente.setVisible(true);
        telaPaciente.mudarNomeBtn();
        telaPaciente.setPainel(painel);
        telaPaciente.setDiagnostico(true);
        telaPaciente.setTelaDiagnostico(this);
        telaPaciente.setLocation(painel.getWidth() / 2 - telaPaciente.getWidth() / 2,
        painel.getHeight() / 2 - telaPaciente.getHeight() / 2);
        painel.add(telaPaciente);
    }//GEN-LAST:event_btnProntuarioActionPerformed

    private void btnDoencaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDoencaActionPerformed
        
        TelaDoenca telaDoenca = new TelaDoenca();
        telaDoenca.setTelaDiagnostico(this);
        telaDoenca.habilitarBtn();
        telaDoenca.setVisible(true);
        telaDoenca.setLocation(painel.getWidth() / 2 - telaDoenca.getWidth() / 2,
        painel.getHeight() / 2 - telaDoenca.getHeight() / 2);
        painel.add(telaDoenca);
        
    }//GEN-LAST:event_btnDoencaActionPerformed

    private void comboStatusActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_comboStatusActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_comboStatusActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        DoencaDao doencaDao = new DoencaDao();
        ProntuarioDao prontuarioDao = new ProntuarioDao();
        DiagnosticoDao diagnosticoDao = new DiagnosticoDao();
        
        int idDoenca = Integer.parseInt(lblIdDoenca.getText().toString());
        int idProntuario = Integer.parseInt(lblIdProntuario.getText().toString());
        String combo;
        if (comboStatus.getSelectedItem().toString().equals("Solucionado"))
            combo = "a";
        else
            combo = "s";
        if (idDoenca > 0 && idProntuario > 0){
            // Instancia os objetos pelos id marcados na label
            Doenca doenca = doencaDao.getById(idDoenca);
            Prontuario prontuario = prontuarioDao.getById(idProntuario);
            
            Diagnostico diagnostico = new Diagnostico(doenca, prontuario, combo);
            diagnosticoDao.inserir(diagnostico);
            JOptionPane.showMessageDialog(rootPane, "Diagnostico inserido");
        }else
            JOptionPane.showMessageDialog(rootPane, "Indique todos os valores acima !");
    }//GEN-LAST:event_btnInserirActionPerformed

    public void setPainel(JDesktopPane painel) {
        this.painel = painel;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDoenca;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnProntuario;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> comboStatus;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblDoenca;
    private javax.swing.JLabel lblIdDoenca;
    private javax.swing.JLabel lblIdProntuario;
    private javax.swing.JLabel lblProntuario;
    // End of variables declaration//GEN-END:variables
}
